#if defined _mewsound_gamedata_included_
#endinput
#endif
#define _mewsound_gamedata_included_

#include <mewsound/info>

#define MEWSOUND_GAMEDATA_FILENAME MEWSOUND_NAME_LOWER ... ".games"

#define MEWSOUND_GAMEDATA_CGAMESERVER "CGameServer"
#define MEWSOUND_GAMEDATA_CGAMECLIENT__SENDSOUND "CGameClient::SendSound"
#define MEWSOUND_GAMEDATA_CGAMESERVER__GETSOUND "CGameServer::GetSound"
#define MEWSOUND_GAMEDATA_CBASECLIENT__GETPLAYERSLOT "CBaseClient::GetPlayerSlot"
#define MEWSOUND_GAMEDATA_SOUNDINFO_T__NENTITYINDEX "SoundInfo_t::nEntityIndex"
#define MEWSOUND_GAMEDATA_SOUNDINFO_T__FVOLUME "SoundInfo_t::fVolume"
#define MEWSOUND_GAMEDATA_SOUNDINFO_T__NSOUNDNUM "SoundInfo_t::nSoundNum"
#define MEWSOUND_GAMEDATA_CGAMECLIENT__THING "CGameClient::thing"
