#if defined _mewsound_info_included_
#endinput
#endif
#define _mewsound_info_included_

#include <mewsound/version>

#define MEWSOUND_NAME "Mewsound"
#define MEWSOUND_NAME_LOWER "mewsound"
#define MEWSOUND_AUTHOR "Mee;w, Haze, Lojka"
#define MEWSOUND_DESCRIPTION "Sound manager for Trikz"
#define MEWSOUND_URL "https://github.com/herbary/mewsound"

#define MEWSOUND_VERSION MEWSOUND_VERSION_IMPL(MEWSOUND_VERSION_MAJOR_STRING, MEWSOUND_VERSION_MINOR_STRING, MEWSOUND_VERSION_PATCH_STRING)
